### ISSUE TITLE
The INST_IO address example is misleading.

### ISSUE THREAD

**Issue by tzxx** [epics-docs/epics-docs#4]
In this document, the INST_IO format is like that:
_#@parm_
but if you put the '#' at the beginning, the INST_IO address will be read as empty string.
Am I miss anything?

**Comment by tzxx** [comment]
> In this document, the INST_IO format is like that:
> _#@parm_
> but if you put the '#' at the beginning, the INST_IO address will be read as empty string.
> Am I miss anything?

In my test, v3.15.5 can parse this kind of address right, but in v7.0.6, the '#' must be removed.

**Comment by dirk-zimoch** [comment]
The INST_IO format has traditionally been `@param`, no `#`. That's how it was documented in the Release 3.14.x Application Developer's Guide. I am pretty sure the `#` at the beginning is wrong.

**Comment by dirk-zimoch** [comment]
Also the document in this project says:

> INST_IO @parm
> 
> parm – Device dependent character string

No # is mentioned there.

**Comment by ttkorhonen** [comment]
tzxx, can you point out which document you were looking at?

**Comment by tzxx** [comment]
> tzxx, can you point out which document you were looking at?
Thanks for the quick reply!
It's here: [hardware-addresses](https://docs.epics-controls.org/en/latest/guides/EPICS_Process_Database_Concepts.html#hardware-addresses)

```
The INST I/O specification is a string that is parsed by the device support. The format of this string is determined by the device support.

#@parm

For INST I/O

@ precedes optional string parm
```

**Comment by tzxx** [comment]
> I try to find the time to update this. However, I would not mind if somebody volunteers to help...

Is that all in this repo? If so I think I can do this.

**Comment by ttkorhonen** [comment]
This text is in this repo so fixing here should do the job. There are links to documents outside this repo elsewhere but they are not relevant in this case. Thank you for offering to help!
If you decide to do the fix, maybe clone first and then create a pull request.

**Comment by dirk-zimoch** [comment]
> However, the # does appear in all older documents, not in App Dev guide but in the Record Ref Manual

Oh right. I just found it in the EPICS 3.13 Record Reference Manual. Must have been there all the time and nobody noticed.
The EPICS 3.13 and 3.14 code at least simply scans the link for `@` (ignoring everything before) and takes the following string.
But when printing back the link, it only prints an initial '@'.

**Comment by tzxx** [comment]
Thanks for your help, I made a pull request here, I've searched all files in this repo, the one in concepts is the only error I found. #5

**Comment by ttkorhonen** [comment]
I merged your change. The document on the web should be up to date, I just checked. I guess this issue can be closed. Thank you for your help, tzxx and Dirk!
