### ISSUE TITLE
Links to adsDriver and autoparamDriver support modules

### ISSUE THREAD

**Issue by zioven** [epics-docs/epics-docs#45]
Hi,

I would propose that the following two modules be added to the list of supported software:

adsDriver:
sources: https://github.com/cosylab/adsDriver
documentation: https://epics.cosylab.com/documentation/adsDriver/

autoparamDriver:
sources: https://github.com/cosylab/autoparamDriver
documentation: https://epics.cosylab.com/documentation/autoparamDriver/

**Comment by Afroza-BNL** [comment]
I have added links to adsDriver and autoparamDriver to the list of supported software.

**Comment by ttkorhonen** [comment]
Please create a pull request and we will take a look and merge (or ask for fixes if there are any issues.)

**Comment by ttkorhonen** [comment]
Implemented and released on docs.epics-controls.org

**Comment by zioven** [comment]
Thank you all for including this links.

**Comment by ttkorhonen** [comment]
There is a link to ADS which seems to be broken...could you maybe take a look and make a new PR?

**Comment by ttkorhonen** [comment]
Sorry, no new PR here is needed, of course. Sorry for the confusion! But @zioven , maybe you want to fix the link on your page.

**Comment by zioven** [comment]
@ttkorhonen Thank you for letting us know, will fix the link on our site.
