### ISSUE TITLE
Link to node-epics-ca

### ISSUE THREAD

**Issue by wanglin86769** [epics-docs/epics-docs#51]
Hello,
There is a maintained version of EPICS CA for Node.js called **node-epics-ca** which is already included in the following EPICS web site,
https://epics.anl.gov/extensions/index.php

The GitHub and npm links for **node-epics-ca** are as follows,
https://github.com/wanglin86769/node-epics-ca
https://www.npmjs.com/package/node-epics-ca

**Comment by minijackson** [comment]
Fixed by #54
