### ISSUE TITLE
Recommend installing from a release tar-file

### ISSUE THREAD

**Issue by anjohnson** [epics-docs/epics-docs#70]
The installation instructions [for Linux](https://docs.epics-controls.org/en/latest/getting-started/installation-linux.html#install-epics) recommend using `git clone` to fetch the source code from the default branch, which isn't really a good idea as it might be in the middle of a transition so could be broken. I think they should show new users how start from a release tar-file first, like the Windows instructions do.

**Comment by ttkorhonen** [comment]
Edited as requested.
